CREATE TABLE IF NOT EXISTS reports (
  id INTEGER PRIMARY KEY,
  app_id TEXT NOT NULL,
  arch TEXT NOT NULL,
  machine_id TEXT NOT NULL,
  os TEXT NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  version TEXT NOT NULL
);
