// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

type Report struct {
	ID        int64
	AppID     string
	Arch      string
	MachineID string
	Os        string
	Version   string
}
