// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package queries

import (
	"context"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO
  reports (app_id, arch, machine_id, os, version)
VALUES
  (?, ?, ?, ?, ?)
`

type CreateReportParams struct {
	AppID     string
	Arch      string
	MachineID string
	Os        string
	Version   string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.ExecContext(ctx, createReport,
		arg.AppID,
		arg.Arch,
		arg.MachineID,
		arg.Os,
		arg.Version,
	)
	return err
}
