// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package queries

import (
	"context"
)

const createRecord = `-- name: CreateRecord :exec
INSERT INTO records (
  uid, data
) VALUES (
  ?, ?
)
`

type CreateRecordParams struct {
	Uid  string
	Data string
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) error {
	_, err := q.db.ExecContext(ctx, createRecord, arg.Uid, arg.Data)
	return err
}
